# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f30b603ff049e75fcfd44eb97573b71fdaf067319a302d46e038dd8ffbdeea94ab6cd0de76bd1b9175b89761472de48fb365fdc7ee8474bf07db5ca77a2f38d8

test:
  secret_key_base: 47802eb87e351cdd49d13d9b0594c66cb79ed9fdc4d65a96b119bcca671a83992cb585134d90447616c4bdc800a03cc2ea4385d74dae22d06035ca642c7a07c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
